### PR TITLE
Create codeunit GetAIMove.al

### PR DESCRIPTION
**Pull request by bwdeleeuw**
Hi Vjeko,

Great contest!

here is my submission. Credit goes to https://stackoverflow.com/users/1524317/kaushik for the algorithm.

I considered MinMax, and alpha-beta pruning, but the search space just seemed to small. The code is still rough, and I really don't like my code around the vector selection, but I couldn't figure out how to fill in an array in AL without specifying each element separately.

Bartel de Leeuw

### CODE REVIEW

**Review by vjekob — APPROVED** [review]
Great submission! Let me see how it fares ;)

**Comment by vjekob** [comment]
Hi Bartel,

Well - you earned your prize :) You just got a standing ovation from my family, that's the only audience I have here. But you get all the credit, and I'll use your solution codeunit to demonstrate to people how easy it is to do event-driven loosely coupled architectures in NAV.

Thanks for participating, and I hope I meet you in person at one of the conferences.

Have a great weekend,

/Vjeko

**Comment by bwdeleeuw** [comment]
Hi Vjeko,

Thanks, however I'll be submitting a improved variant later today. This one fails on Edge starts by the x-player. Should teach me not to submit code in the middle of the night! 

I have enjoyed your content and presentations over the last few years, and look forward to meeting you in person as well.

Have a great weekend,

Bartel

**Comment by vjekob** [comment]
Correct, I just beat it. Thanks for letting me know, I was just about to post the announcement on my blog. You did get a standing ovation from my family, though :)

In any case, I'll let it stay, to stay true to my challenge - the algorithm must not lose ;)

Looking forward to the updated submission, and thanks for the kind words!

**Comment by bwdeleeuw** [comment]
Hi Vjeko, I submitted a new Pull Request with a fix for the edge-start loss.

NB, this is not the strongest AI player, but the code is a lot more readable than a MinMax or NegaMax routine.

Bartel

**Comment by vjekob** [comment]
Hi Bartel! Thanks for another submission. I've now merged it into master and published a blog post. Thanks for contributing!

**Comment by bwdeleeuw** [comment]
Hi Vjeko,

I am honored. I’m excited about the new development environment. This was my first project with it after the ‘Hello World’ template, and I like the current state of the tools, and am interested to see where the NAV devs will take it. 

Thanks again,

Bartel

**Pull request merged**
